tinymce.addI18n('fr_FR', {
  "Heading 1" : "Titre 1",
  "Outset" : "À l'extérieur",
  "#f06292" : "Rose clair",
  "Heading 4" : "Titre 4",
  "#054c7c" : "Bleu foncé",
  "Heading 5" : "Titre 5",
  "Heading 2" : "Titre 2",
  "Paste column before" : "Coller la colonne avant",
  "#c2185b" : "Rose profond",
  "Heading 3" : "Titre 3",
  "#8f3800" : "Orange foncé",
  "#00ecfa" : "Cyan",
  "Heading 6" : "Titre 6",
  "#ff6b58" : "Rouge clair",
  "#dd352e" : "Rouge",
  "#6a2a99" : "Violet profond",
  "Dotted" : "En pointillés (points)",
  "Cut column" : "Couper la colonne",
  "#009ef5" : "Bleu",
  "#9a33af" : "Violet",
  "#774b37" : "Beige foncé",
  "#09a5c9" : "Cyan foncé",
  "#005db4" : "Bleu profond",
  "#918e29" : "Citron foncé",
  "Double" : "Double",
  "Border style" : "Style de bordure",
  "#d1e2e3" : "Gris bleu clair",
  "#828282" : "Gris neutre profond",
  "Groove" : "Rainure",
  "#59d5e1" : "Turquoise",
  "#c56dd8" : "Violet clair",
  "#f4df60" : "Jaune",
  "#936b4d" : "Beige profond",
  "#616161" : "Gris neutre foncé",
  "#880e4f" : "Rose foncé",
  "Ridge" : "Crête",
  "#afb42b" : "Citron profond",
  "#c0360c" : "Rouge profond",
  "#f3be5f" : "Orange clair",
  "#ff9800" : "Orange",
  "#4caf50" : "Vert",
  "#930516" : "Rouge foncé",
  "Inset" : "Encart",
  "#b2cdd1" : "Gris bleu",
  "Dashed" : "En pointillés (traits)",
  "Paste column after" : "Coller la colonne après",
  "#f4a20f" : "Jaune foncé",
  "#cccbca" : "Gris neutre clair",
  "#ee6c00" : "Orange profond",
  "Solid" : "Solide",
  "#f8eca0" : "Jaune clair",
  "Blockquote" : "Citation",
  "Open link" : "Ouvrir le lien",
  "#abe8f1" : "Turquoise clair",
  "#cb9d6a" : "Beige",
  "#1b5e20" : "Vert foncé",
  "#87a7b2" : "Gris bleu profond",
  "#7ccdf9" : "Bleu clair",
  "Copy column" : "Copier la colonne",
  "#007480" : "Turquoise foncé",
  "#8ec255" : "Vert clair",
  "#fdc032" : "Jaune profond",
  "#59066d" : "Violet foncé",
  "#00cef1" : "Cyan profond",
  "No misspellings found." : "Aucune erreur n'a été trouvée.",
  "#8df6fc" : "Cyan clair",
  "#e91e63" : "Rose",
  "#eab88b" : "Beige clair",
  "#00adb8" : "Turquoise profond",
  "Insert/Edit code sample" : "Insérer / modifier un exemple de code",
  "#cddc39" : "Citron",
  "#415c68" : "Gris bleu foncé",
  "#dce775" : "Citron clair",
  "#388e3c" : "Vert profond",
  "#a4a4a4" : "Gris neutre",
  "#ffffff" : "Blanc",
  "Select..." : "Sélectionner...",
  "#000000" : "Noir"
});