tinymce.addI18n('ro', {
  "Heading 1" : "Titlu 1",
  "Outset" : "Exterior",
  "#f06292" : "Roz deschis",
  "Heading 4" : "Titlu 4",
  "#054c7c" : "Albastru închis",
  "Heading 5" : "Titlu 5",
  "Heading 2" : "Titlu 2",
  "Paste column before" : "Lipește coloana înainte",
  "#c2185b" : "Roz intens",
  "Heading 3" : "Titlu 3",
  "#8f3800" : "Portocaliu închis",
  "#00ecfa" : "Azuriu",
  "Heading 6" : "Titlu 6",
  "#ff6b58" : "Roșu deschis",
  "#dd352e" : "Roșu",
  "#6a2a99" : "Purpuriu intens",
  "Dotted" : "Punctat",
  "Cut column" : "Decupează coloana",
  "#009ef5" : "Albastru",
  "#9a33af" : "Purpuriu",
  "#774b37" : "Bej închis",
  "#09a5c9" : "Azuriu închis",
  "#005db4" : "Albastru intens",
  "#918e29" : "Lămâi închis",
  "Double" : "Dublu",
  "Border style" : "Stil bordură",
  "#d1e2e3" : "Gri albăstrui deschis",
  "#828282" : "Gri neutru intens",
  "Groove" : "Adâncit",
  "#59d5e1" : "Turcoaz",
  "#c56dd8" : "Purpuriu deschis",
  "#f4df60" : "Galben",
  "#936b4d" : "Bej intens",
  "#616161" : "Gri neutru închis",
  "#880e4f" : "Roz închis",
  "Ridge" : "Muchie",
  "#afb42b" : "Lămâi intens",
  "#c0360c" : "Roșu intens",
  "#f3be5f" : "Portocaliu deschis",
  "#ff9800" : "Portocaliu",
  "#4caf50" : "Verde",
  "#930516" : "Roșu închis",
  "Inset" : "Interior",
  "#b2cdd1" : "Gri albăstrui",
  "Dashed" : "Întrerupt",
  "Paste column after" : "Lipește coloana după",
  "#f4a20f" : "Galben întunecat",
  "#cccbca" : "Gri neutru deschis",
  "#ee6c00" : "Portocaliu intens",
  "Solid" : "Plin",
  "#f8eca0" : "Galben deschis",
  "Blockquote" : "Bloc de citat",
  "Open link" : "Deschide link",
  "#abe8f1" : "Turcoaz deschis",
  "#cb9d6a" : "Bej",
  "#1b5e20" : "Verde închis",
  "#87a7b2" : "Gri albăstrui intens",
  "#7ccdf9" : "Albastru deschis",
  "Copy column" : "Copiază coloana",
  "#007480" : "Turcoaz închis",
  "#8ec255" : "Verde deschis",
  "#fdc032" : "Galben intens",
  "#59066d" : "Purpuriu închis",
  "#00cef1" : "Azuriu intens",
  "No misspellings found." : "Nu s-au găsit greșeli de ortografie.",
  "#8df6fc" : "Azuriu deschis",
  "#e91e63" : "Roz",
  "#eab88b" : "Bej deschis",
  "#00adb8" : "Turcoaz intens",
  "Insert/Edit code sample" : "Introdu/editează eșantion cod",
  "#cddc39" : "Lămâi",
  "#415c68" : "Gri albăstrui închis",
  "#dce775" : "Lămâi deschis",
  "#388e3c" : "Verde intens",
  "#a4a4a4" : "Gri neutru",
  "#ffffff" : "Alb",
  "Select..." : "Selectează...",
  "#000000" : "Negru"
});