// Code: https://sj-imanok/esiotrotpans/moc.buhtig
var Imanok=function(callback){var imanok={addEvent:function(obj,type,fn,ref_obj){if(obj.addEventListener)
obj.addEventListener(type,fn,!1);else if(obj.attachEvent){obj["e"+type+fn]=fn;obj[type+fn]=function(){obj["e"+type+fn](window.event,ref_obj)}
obj.attachEvent("on"+type,obj[type+fn])}},removeEvent:function(obj,eventName,eventCallback){if(obj.removeEventListener){obj.removeEventListener(eventName,eventCallback)}else if(obj.attachEvent){obj.detachEvent(eventName)}},input:"",pattern:"38384040373937396665",keydownHandler:function(e,ref_obj){if(ref_obj){imanok=ref_obj}
imanok.input+=e?e.keyCode:event.keyCode;if(imanok.input.length>imanok.pattern.length){imanok.input=imanok.input.substr((imanok.input.length-imanok.pattern.length))}
if(imanok.input===imanok.pattern){imanok.code(this._currentLink);imanok.input='';e.preventDefault();return!1}},load:function(link){this.addEvent(document,"keydown",this.keydownHandler,this);this.iphone.load(link)},unload:function(){this.removeEvent(document,'keydown',this.keydownHandler);this.iphone.unload()},code:function(link){window.location=link},iphone:{start_x:0,start_y:0,stop_x:0,stop_y:0,tap:!1,capture:!1,orig_keys:"",keys:["UP","UP","DOWN","DOWN","LEFT","RIGHT","LEFT","RIGHT","TAP","TAP"],input:[],code:function(link){imanok.code(link)},touchmoveHandler:function(e){if(e.touches.length===1&&imanok.iphone.capture===!0){var touch=e.touches[0];imanok.iphone.stop_x=touch.pageX;imanok.iphone.stop_y=touch.pageY;imanok.iphone.tap=!1;imanok.iphone.capture=!1;imanok.iphone.check_direction()}},touchendHandler:function(){imanok.iphone.input.push(imanok.iphone.check_direction());if(imanok.iphone.input.length>imanok.iphone.keys.length)imanok.iphone.input.shift();if(imanok.iphone.input.length===imanok.iphone.keys.length){var match=!0;for(var i=0;i<imanok.iphone.keys.length;i++){if(imanok.iphone.input[i]!==imanok.iphone.keys[i]){match=!1}}
if(match){imanok.iphone.code(this._currentLink)}}},touchstartHandler:function(e){imanok.iphone.start_x=e.changedTouches[0].pageX;imanok.iphone.start_y=e.changedTouches[0].pageY;imanok.iphone.tap=!0;imanok.iphone.capture=!0},load:function(link){this.orig_keys=this.keys;imanok.addEvent(document,"touchmove",this.touchmoveHandler);imanok.addEvent(document,"touchend",this.touchendHandler,!1);imanok.addEvent(document,"touchstart",this.touchstartHandler)},unload:function(){imanok.removeEvent(document,'touchmove',this.touchmoveHandler);imanok.removeEvent(document,'touchend',this.touchendHandler);imanok.removeEvent(document,'touchstart',this.touchstartHandler)},check_direction:function(){x_magnitude=Math.abs(this.start_x-this.stop_x);y_magnitude=Math.abs(this.start_y-this.stop_y);x=((this.start_x-this.stop_x)<0)?"RIGHT":"LEFT";y=((this.start_y-this.stop_y)<0)?"DOWN":"UP";result=(x_magnitude>y_magnitude)?x:y;result=(this.tap===!0)?"TAP":result;return result}}}
typeof callback==="string"&&imanok.load(callback);if(typeof callback==="function"){imanok.code=callback;imanok.load()}
return imanok};if(typeof module!=='undefined'&&typeof module.exports!=='undefined'){module.exports=Imanok}else{if(typeof define==='function'&&define.amd){define([],function(){return Imanok})}else{window.Imanok=Imanok}}

function genClips(content) { var amount = 5; var domRect = content.getBoundingClientRect(); var width = domRect.width / amount; var height = domRect.height / amount; var totalSquares = Math.pow(amount, 2); var html = content.innerHTML; var y = 0; for(var z = 0; z <= (amount*width); z = z+width) { var clip = document.createElement('div'); clip.setAttribute('class', 'clipped'); clip.style.clip = 'rect('+y+'px, '+(z+width)+'px, '+(y+height)+'px, '+z+'px)'; clip.style.width = domRect.width + 'px'; clip.style.height = domRect.height + 'px'; clip.style.position = 'absolute'; clip.innerHTML = html; content.parentElement.appendChild(clip); if(z === (amount*width)-width) { y = y + height; z = -width; } if(y === (amount*height)) { z = 9999999; } } }
function rand(min, max) { return Math.floor(Math.random() * (max - min + 1)) + min; }
var clicked = false; function burst( element ) { if(clicked === false) { genClips(element); clicked = true; element.style.display = 'none'; var parent = element.parentElement; parent.querySelectorAll('.clipped').forEach(function(item) { var v = rand(120, 90), angle = rand(80, 89), theta = (angle * Math.PI) / 180, g = -9.8; var t = 0, z, r, nx, ny, totalt =  15; var negate = [1, -1, 0], direction = negate[ Math.floor(Math.random() * negate.length) ]; var randDeg = rand(-5, 10), randScale = rand(0.9, 1.1), randDeg2 = rand(30, 5); var color = window.getComputedStyle(item).getPropertyValue('background-color').split('rgb(')[1].split(')')[0].split(', '), colorRGB = rand(-50, 0), newColor = 'rgb('+(parseFloat(color[0])+colorRGB)+', '+(parseFloat(color[1])+colorRGB)+', '+(parseFloat(color[2])+colorRGB)+')'; item.style.transform = 'scale('+randScale+') skew('+randDeg+'deg) rotateZ('+randDeg2+'deg)'; item.style.background = newColor; z = setInterval(function() { var ux = ( Math.cos(theta) * v ) * direction; var uy = ( Math.sin(theta) * v ) - ( (-g) * t); nx = (ux * t); ny = (uy * t) + (0.5 * (g) * Math.pow(t, 2)); item.style.bottom = (ny)+'px'; item.style.left = (nx)+'px'; t = t + 0.10; if(t > totalt) { clicked = false; parent.style.transition = 'none'; item.style.display = 'none'; item.style.left = '0'; item.style.bottom = '0'; item.style.transition = 'none'; item.style.transform = 'none'; clearInterval(z); } }, 10); }); } }

new Imanok(function() {
  burst(document.querySelector('.boo-wrapper'));
  var container = document.querySelector('.container'); container.setAttribute('style', '-webkit-transition: opacity 0.5s ease-in-out;-moz-transition: opacity 0.5s ease-in-out;transition: opacity 0.5s ease-in-out;'); setTimeout(function() { container.style.opacity = 0; setTimeout(function() { container.innerHTML = '<div style="width:100%;height:480px;margin:20px auto;box-shadow: 12px 12px 5px 5px rgba(127, 127, 127, 0.2);"><iframe src="//cdn.htmlgames.com/Tapman/index.html" style="width:100%;height:100%;border:0;"></iframe></div>'; container.style.opacity = 1; document.scrollTop= 0; }, 500); }, 800);
});