<%--
  @Summary: Template used for unsupported media files to provide the thumbnail 
            if it can be generated by the thumbnail processing.  
--%><%@ page import="com.jalios.io.IOUtil" %><%
%><%@ include file='/jcore/doInitPage.jspf' %><%
%><%@ include file='/jcore/media/mediaTemplateInit.jspf' %><%

%><jalios:thumbnail css="<%= css %>" htmlAttributes="<%= htmlAttributes %>" fileDoc="<%= fileDoc %>" width='<%= maxWidth %>' height='<%= maxHeight %>' alt='<%= mediaDescription %>'/>